# Generated by Django 6.0.2 on 2026-02-28 22:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal_contato_alter_animal_cuidador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.CharField(max_length=255),
        ),
    ]
