# Generated by Django 6.0.2 on 2026-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_campanha_descricao_alter_campanha_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='porte',
            field=models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=10, null=True, verbose_name='Porte'),
        ),
    ]
