# Generated by Django 6.0.2 on 2026-02-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_animal_porte'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
