# Generated by Django 6.0.2 on 2026-03-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(choices=[('Menos de 6 meses', 'Menos de 6 meses'), ('7 a 11 meses', '7 a 11 meses'), ('1 ano', '1 ano'), ('2 anos', '2 anos'), ('3 anos', '3 anos'), ('4 anos', '4 anos'), ('5 anos', '5 anos'), ('6 anos', '6 anos'), ('7 ou mais', '7 ou mais')], max_length=20, verbose_name='Idade'),
        ),
    ]
