# Generated by Django 6.0.2 on 2026-03-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_animal_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='contato',
        ),
        migrations.AddField(
            model_name='animal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='animal',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número com DDD', max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
