# Generated by Django 6.0.2 on 2026-03-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_animal_contato_animal_email_animal_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='animais_extras/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_extras', to='core.animal')),
            ],
        ),
    ]
