# Generated by Django 5.2.7 on 2025-11-04 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='contato',
            field=models.CharField(blank=True, help_text='Telefone ou WhatsApp para contato', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to=settings.AUTH_USER_MODEL),
        ),
    ]
